// 裝備類型定義 - 共用常數
export const EQUIPMENT_TYPES = {
  HELMET: "頭盔",
  TOPWEAR: "上衣",
  BOTTOMWEAR: "下衣",
  OVERALL: "套服",
  SHOES: "鞋子",
  GLOVES: "手套",
  CAPE: "披風",
  SHIELD: "盾牌",
  EARRING: "耳環",
  EYE_ACCESSORY: "眼部裝飾",
  FACE_ACCESSORY: "臉飾",
  PENDANT: "項鍊",
  BELT: "腰帶",
  ONE_HANDED_SWORD: "單手劍",
  TWO_HANDED_SWORD: "雙手劍",
  ONE_HANDED_AXE: "單手斧",
  TWO_HANDED_AXE: "雙手斧",
  ONE_HANDED_BW: "單手棍",
  TWO_HANDED_BW: "雙手棍",
  SPEAR: "槍",
  POLE_ARM: "矛",
  BOW: "弓",
  CROSSBOW: "弩",
  WAND: "短杖",
  STAFF: "長杖",
  DAGGER: "短劍",
  CLAW: "拳套",
  KNUCKLE: "指虎",
  GUN: "手槍",
} as const;
