import { EQUIPMENT_TYPES } from "./equipmentTypes.ts";

// 裝備分類
export const EQUIPMENT_CATEGORIES = {
  ARMOR: "防具",
  WEAPONS: "武器",
  ACCESSORIES: "飾品",
} as const;

// 實際有卷軸數據的裝備類型（基於scrolls.ts中的實際數據）
export const EQUIPMENT_TYPES_WITH_SCROLLS = [
  // 防具類
  EQUIPMENT_TYPES.HELMET, // 頭盔
  EQUIPMENT_TYPES.TOPWEAR, // 上衣
  EQUIPMENT_TYPES.BOTTOMWEAR, // 下衣
  EQUIPMENT_TYPES.OVERALL, // 套服
  EQUIPMENT_TYPES.SHOES, // 鞋子
  EQUIPMENT_TYPES.GLOVES, // 手套
  EQUIPMENT_TYPES.CAPE, // 披風
  EQUIPMENT_TYPES.SHIELD, // 盾牌

  // 武器類
  EQUIPMENT_TYPES.ONE_HANDED_SWORD, // 單手劍
  EQUIPMENT_TYPES.TWO_HANDED_SWORD, // 雙手劍
  EQUIPMENT_TYPES.ONE_HANDED_AXE, // 單手斧
  EQUIPMENT_TYPES.TWO_HANDED_AXE, // 雙手斧
  EQUIPMENT_TYPES.ONE_HANDED_BW, // 單手棍
  EQUIPMENT_TYPES.TWO_HANDED_BW, // 雙手棍
  EQUIPMENT_TYPES.SPEAR, // 槍
  EQUIPMENT_TYPES.POLE_ARM, // 矛
  EQUIPMENT_TYPES.BOW, // 弓
  EQUIPMENT_TYPES.CROSSBOW, // 弩
  EQUIPMENT_TYPES.WAND, // 短杖
  EQUIPMENT_TYPES.STAFF, // 長杖
  EQUIPMENT_TYPES.DAGGER, // 短劍
  EQUIPMENT_TYPES.CLAW, // 拳套
  EQUIPMENT_TYPES.KNUCKLE, // 指虎
  EQUIPMENT_TYPES.GUN, // 手槍

  // 飾品類
  EQUIPMENT_TYPES.EARRING, // 耳環
  EQUIPMENT_TYPES.EYE_ACCESSORY, // 眼部裝飾
  EQUIPMENT_TYPES.FACE_ACCESSORY, // 臉飾
  EQUIPMENT_TYPES.PENDANT, // 項鍊
  EQUIPMENT_TYPES.BELT, // 腰帶
] as const;

// 按類別分組的裝備類型（只包含有卷軸數據的）
export const EQUIPMENT_BY_CATEGORY_WITH_SCROLLS = {
  [EQUIPMENT_CATEGORIES.ARMOR]: [
    EQUIPMENT_TYPES.HELMET,
    EQUIPMENT_TYPES.TOPWEAR,
    EQUIPMENT_TYPES.BOTTOMWEAR,
    EQUIPMENT_TYPES.OVERALL,
    EQUIPMENT_TYPES.SHOES,
    EQUIPMENT_TYPES.GLOVES,
    EQUIPMENT_TYPES.CAPE,
    EQUIPMENT_TYPES.SHIELD,
  ],
  [EQUIPMENT_CATEGORIES.WEAPONS]: [
    EQUIPMENT_TYPES.ONE_HANDED_SWORD,
    EQUIPMENT_TYPES.TWO_HANDED_SWORD,
    EQUIPMENT_TYPES.ONE_HANDED_AXE,
    EQUIPMENT_TYPES.TWO_HANDED_AXE,
    EQUIPMENT_TYPES.ONE_HANDED_BW,
    EQUIPMENT_TYPES.TWO_HANDED_BW,
    EQUIPMENT_TYPES.SPEAR,
    EQUIPMENT_TYPES.POLE_ARM,
    EQUIPMENT_TYPES.BOW,
    EQUIPMENT_TYPES.CROSSBOW,
    EQUIPMENT_TYPES.WAND,
    EQUIPMENT_TYPES.STAFF,
    EQUIPMENT_TYPES.DAGGER,
    EQUIPMENT_TYPES.CLAW,
    EQUIPMENT_TYPES.KNUCKLE,
    EQUIPMENT_TYPES.GUN,
  ],
  [EQUIPMENT_CATEGORIES.ACCESSORIES]: [
    EQUIPMENT_TYPES.EARRING,
    EQUIPMENT_TYPES.EYE_ACCESSORY,
    EQUIPMENT_TYPES.FACE_ACCESSORY,
    EQUIPMENT_TYPES.PENDANT,
    EQUIPMENT_TYPES.BELT,
  ],
};

// 所有可用的裝備類型（扁平化）
export const AVAILABLE_EQUIPMENT_TYPES = Object.values(
  EQUIPMENT_BY_CATEGORY_WITH_SCROLLS
).flat();

// 裝備圖示映射（使用更炫砲的 emoji 組合）
export const EQUIPMENT_ICONS: Record<string, string> = {
  [EQUIPMENT_TYPES.HELMET]: "⚔️",
  [EQUIPMENT_TYPES.TOPWEAR]: "🛡️",
  [EQUIPMENT_TYPES.BOTTOMWEAR]: "🦵",
  [EQUIPMENT_TYPES.OVERALL]: "🥋",
  [EQUIPMENT_TYPES.SHOES]: "👢",
  [EQUIPMENT_TYPES.GLOVES]: "🧤",
  [EQUIPMENT_TYPES.CAPE]: "🦸",
  [EQUIPMENT_TYPES.SHIELD]: "🛡️",
  [EQUIPMENT_TYPES.EARRING]: "💎",
  [EQUIPMENT_TYPES.EYE_ACCESSORY]: "🥽",
  [EQUIPMENT_TYPES.FACE_ACCESSORY]: "😎",
  [EQUIPMENT_TYPES.PENDANT]: "💍",
  [EQUIPMENT_TYPES.BELT]: "⭐",
  [EQUIPMENT_TYPES.ONE_HANDED_SWORD]: "⚔️",
  [EQUIPMENT_TYPES.TWO_HANDED_SWORD]: "🗡️",
  [EQUIPMENT_TYPES.ONE_HANDED_AXE]: "🪓",
  [EQUIPMENT_TYPES.TWO_HANDED_AXE]: "⚒️",
  [EQUIPMENT_TYPES.ONE_HANDED_BW]: "🏏",
  [EQUIPMENT_TYPES.TWO_HANDED_BW]: "🥍",
  [EQUIPMENT_TYPES.SPEAR]: "🔱",
  [EQUIPMENT_TYPES.POLE_ARM]: "⚡",
  [EQUIPMENT_TYPES.BOW]: "🏹",
  [EQUIPMENT_TYPES.CROSSBOW]: "🎯",
  [EQUIPMENT_TYPES.WAND]: "🪄",
  [EQUIPMENT_TYPES.STAFF]: "🔮",
  [EQUIPMENT_TYPES.DAGGER]: "🗡️",
  [EQUIPMENT_TYPES.CLAW]: "🥊",
  [EQUIPMENT_TYPES.KNUCKLE]: "👊",
  [EQUIPMENT_TYPES.GUN]: "🔫",
};

// 可用的屬性類型（基於scrolls.ts中實際存在的屬性）
export const ATTRIBUTE_TYPES = [
  "物攻",
  "魔攻",
  "敏捷",
  "智力",
  "力量",
  "幸運",
  "體力",
  "HP",
  "MP",
  "物防",
  "魔防",
  "命中率",
  "移動速度",
  "跳躍力",
] as const;

export type AttributeType = (typeof ATTRIBUTE_TYPES)[number];

// 屬性圖示映射（更炫砲的設計）
export const ATTRIBUTE_ICONS: Record<string, string> = {
  物攻: "⚔️",
  魔攻: "🔮",
  敏捷: "⚡",
  智力: "🧠",
  力量: "💪",
  幸運: "🍀",
  體力: "❤️‍🔥",
  HP: "❤️",
  MP: "💙",
  物防: "🛡️",
  魔防: "✨",
  命中率: "🎯",
  移動速度: "��",
  跳躍力: "🦘",
};

// 屬性分類
export const ATTRIBUTE_CATEGORIES = {
  ATTACK: "攻擊",
  BASIC: "基本能力",
  VITALITY: "生命力",
  DEFENSE: "防禦",
  SPECIAL: "特殊",
} as const;

// 按類別分組的屬性
export const ATTRIBUTES_BY_CATEGORY = {
  [ATTRIBUTE_CATEGORIES.ATTACK]: ["物攻", "魔攻"],
  [ATTRIBUTE_CATEGORIES.BASIC]: ["敏捷", "智力", "力量", "幸運", "體力"],
  [ATTRIBUTE_CATEGORIES.VITALITY]: ["HP", "MP"],
  [ATTRIBUTE_CATEGORIES.DEFENSE]: ["物防", "魔防"],
  [ATTRIBUTE_CATEGORIES.SPECIAL]: ["命中率", "移動速度", "跳躍力"],
} as const;
