import { EQUIPMENT_TYPES } from "./equipmentTypes.ts";

// 卷軸資料類型定義
export interface ScrollEffect {
  stat: string;
  value: number;
}

export interface Scroll {
  id: string;
  name: string;
  successRate: number;
  equipmentType: string;
  primaryEffect: ScrollEffect;
  secondaryEffects?: ScrollEffect[];
}

// 所有卷軸資料 - 186種卷軸
export const SCROLLS: Scroll[] = [
  // 10%成功率卷軸 (69種)
  {
    id: "helmet_dex_10",
    name: "頭盔敏捷卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "敏捷", value: 3 },
  },
  {
    id: "helmet_int_10",
    name: "頭盔智力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "智力", value: 3 },
  },
  {
    id: "helmet_hp_10",
    name: "頭盔體力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "HP", value: 30 },
  },
  {
    id: "helmet_def_10",
    name: "頭盔防禦力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "物防", value: 5 },
    secondaryEffects: [
      { stat: "魔防", value: 3 },
      { stat: "命中率", value: 1 },
    ],
  },
  {
    id: "topwear_str_10",
    name: "上衣力量卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "力量", value: 3 },
  },
  {
    id: "topwear_luk_10",
    name: "上衣幸運卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "幸運", value: 3 },
  },
  {
    id: "topwear_hp_10",
    name: "上衣體力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "HP", value: 30 },
  },
  {
    id: "topwear_def_10",
    name: "上衣防禦力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "物防", value: 5 },
    secondaryEffects: [
      { stat: "魔防", value: 3 },
      { stat: "HP", value: 10 },
    ],
  },
  {
    id: "bottomwear_dex_10",
    name: "下衣敏捷性卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "敏捷", value: 3 },
    secondaryEffects: [
      { stat: "命中率", value: 2 },
      { stat: "速度", value: 1 },
    ],
  },
  {
    id: "bottomwear_hp_10",
    name: "下衣體力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "HP", value: 30 },
  },
  {
    id: "bottomwear_jump_10",
    name: "下衣跳躍力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "迴避率", value: 2 },
    secondaryEffects: [{ stat: "跳躍力", value: 4 }],
  },
  {
    id: "bottomwear_def_10",
    name: "下衣防禦力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "物防", value: 5 },
    secondaryEffects: [
      { stat: "魔防", value: 3 },
      { stat: "HP", value: 10 },
    ],
  },
  {
    id: "overall_str_10",
    name: "套服力量卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "力量", value: 5 },
    secondaryEffects: [
      { stat: "物防", value: 3 },
      { stat: "HP", value: 5 },
    ],
  },
  {
    id: "overall_dex_10",
    name: "套服敏捷卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "敏捷", value: 5 },
    secondaryEffects: [
      { stat: "命中率", value: 3 },
      { stat: "速度", value: 1 },
    ],
  },
  {
    id: "overall_int_10",
    name: "套服智力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "智力", value: 5 },
    secondaryEffects: [
      { stat: "魔防", value: 3 },
      { stat: "HP", value: 10 },
    ],
  },
  {
    id: "overall_def_10",
    name: "套服防禦力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "物防", value: 5 },
    secondaryEffects: [
      { stat: "魔防", value: 3 },
      { stat: "HP", value: 10 },
    ],
  },
  {
    id: "shoes_dex_10",
    name: "鞋子敏捷性卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SHOES,
    primaryEffect: { stat: "迴避率", value: 5 },
    secondaryEffects: [
      { stat: "命中率", value: 3 },
      { stat: "速度", value: 1 },
    ],
  },
  {
    id: "shoes_speed_10",
    name: "鞋子移動速度卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SHOES,
    primaryEffect: { stat: "速度", value: 3 },
  },
  {
    id: "shoes_jump_10",
    name: "鞋子跳躍力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SHOES,
    primaryEffect: { stat: "跳躍力", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "速度", value: 1 },
    ],
  },
  {
    id: "gloves_hp_10",
    name: "手套體力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.GLOVES,
    primaryEffect: { stat: "HP", value: 30 },
  },
  {
    id: "gloves_dex_10",
    name: "手套敏捷性卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.GLOVES,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "迴避率", value: 1 },
    ],
  },
  {
    id: "gloves_att_10",
    name: "手套攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.GLOVES,
    primaryEffect: { stat: "物攻", value: 3 },
  },
  {
    id: "cape_str_10",
    name: "披風力量卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "力量", value: 3 },
  },
  {
    id: "cape_dex_10",
    name: "披風敏捷性卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "敏捷", value: 3 },
  },
  {
    id: "cape_int_10",
    name: "披風智力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "智力", value: 3 },
  },
  {
    id: "cape_luk_10",
    name: "披風幸運卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "幸運", value: 3 },
  },
  {
    id: "cape_hp_10",
    name: "披風體力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "HP", value: 20 },
  },
  {
    id: "cape_mp_10",
    name: "披風魔力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "MP", value: 20 },
  },
  {
    id: "cape_def_10",
    name: "披風防禦力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "物防", value: 5 },
    secondaryEffects: [
      { stat: "魔防", value: 3 },
      { stat: "HP", value: 10 },
    ],
  },
  {
    id: "cape_mdef_10",
    name: "披風魔防卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "魔防", value: 5 },
    secondaryEffects: [
      { stat: "物防", value: 3 },
      { stat: "MP", value: 10 },
    ],
  },
  {
    id: "shield_str_10",
    name: "盾牌力量卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "力量", value: 3 },
  },
  {
    id: "shield_luk_10",
    name: "盾牌幸運卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "幸運", value: 3 },
  },
  {
    id: "shield_hp_10",
    name: "盾牌體力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "HP", value: 30 },
  },
  {
    id: "shield_def_10",
    name: "盾牌防禦力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "物防", value: 5 },
    secondaryEffects: [
      { stat: "魔防", value: 3 },
      { stat: "HP", value: 10 },
    ],
  },
  {
    id: "eye_dex_10",
    name: "眼部裝飾敏捷卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.EYE_ACCESSORY,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [{ stat: "敏捷", value: 1 }],
  },
  {
    id: "eye_luk_10",
    name: "眼部裝飾幸運卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.EYE_ACCESSORY,
    primaryEffect: { stat: "幸運", value: 3 },
    secondaryEffects: [{ stat: "魔防", value: 2 }],
  },
  {
    id: "earring_dex_10",
    name: "耳環敏捷卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "敏捷", value: 3 },
  },
  {
    id: "earring_int_10",
    name: "耳環智力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "魔攻", value: 5 },
    secondaryEffects: [
      { stat: "智力", value: 3 },
      { stat: "魔防", value: 1 },
    ],
  },
  {
    id: "earring_luk_10",
    name: "耳環幸運卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "幸運", value: 3 },
  },
  {
    id: "earring_hp_10",
    name: "耳環體力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "HP", value: 30 },
  },
  {
    id: "pendant_str_10",
    name: "項鍊力量卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "力量", value: 3 },
  },
  {
    id: "pendant_dex_10",
    name: "項鍊敏捷卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "敏捷", value: 3 },
  },
  {
    id: "pendant_int_10",
    name: "項鍊智力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "智力", value: 3 },
  },
  {
    id: "pendant_luk_10",
    name: "項鍊幸運卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "幸運", value: 3 },
  },
  {
    id: "1h_sword_att_10",
    name: "單手劍攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_SWORD,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "1h_sword_acc_10",
    name: "單手劍命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_SWORD,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "2h_sword_att_10",
    name: "雙手劍攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_SWORD,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "2h_sword_acc_10",
    name: "雙手劍命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_SWORD,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "1h_axe_att_10",
    name: "單手斧攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_AXE,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "1h_axe_acc_10",
    name: "單手斧命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_AXE,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "2h_axe_att_10",
    name: "雙手斧攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_AXE,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "2h_axe_acc_10",
    name: "雙手斧命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_AXE,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "1h_bw_att_10",
    name: "單手棍攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_BW,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "1h_bw_acc_10",
    name: "單手棍命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_BW,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "2h_bw_att_10",
    name: "雙手棍攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_BW,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "2h_bw_acc_10",
    name: "雙手棍命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_BW,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "spear_att_10",
    name: "槍攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SPEAR,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "spear_acc_10",
    name: "槍命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.SPEAR,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "polearm_att_10",
    name: "矛攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.POLE_ARM,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "polearm_acc_10",
    name: "矛命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.POLE_ARM,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "bow_att_10",
    name: "弓攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.BOW,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "命中率", value: 3 },
      { stat: "敏捷", value: 1 },
    ],
  },
  {
    id: "crossbow_att_10",
    name: "弩攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CROSSBOW,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "命中率", value: 3 },
      { stat: "敏捷", value: 1 },
    ],
  },
  {
    id: "wand_matt_10",
    name: "短杖魔力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.WAND,
    primaryEffect: { stat: "魔攻", value: 5 },
    secondaryEffects: [
      { stat: "智力", value: 3 },
      { stat: "魔防", value: 1 },
    ],
  },
  {
    id: "staff_matt_10",
    name: "長杖魔力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.STAFF,
    primaryEffect: { stat: "魔攻", value: 5 },
    secondaryEffects: [
      { stat: "智力", value: 3 },
      { stat: "魔防", value: 1 },
    ],
  },
  {
    id: "dagger_att_10",
    name: "短劍攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.DAGGER,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "幸運", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "claw_att_10",
    name: "拳套攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.CLAW,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "命中率", value: 3 },
      { stat: "幸運", value: 1 },
    ],
  },
  {
    id: "knuckle_att_10",
    name: "指虎攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.KNUCKLE,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "力量", value: 3 },
      { stat: "物防", value: 1 },
    ],
  },
  {
    id: "knuckle_acc_10",
    name: "指虎命中率卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.KNUCKLE,
    primaryEffect: { stat: "命中率", value: 5 },
    secondaryEffects: [
      { stat: "敏捷", value: 3 },
      { stat: "物攻", value: 3 },
    ],
  },
  {
    id: "gun_att_10",
    name: "手槍攻擊力卷軸10%",
    successRate: 10,
    equipmentType: EQUIPMENT_TYPES.GUN,
    primaryEffect: { stat: "物攻", value: 5 },
    secondaryEffects: [
      { stat: "命中率", value: 3 },
      { stat: "敏捷", value: 1 },
    ],
  },

  // 60%成功率卷軸 (69種)
  {
    id: "helmet_dex_60",
    name: "頭盔敏捷卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "敏捷", value: 2 },
  },
  {
    id: "helmet_int_60",
    name: "頭盔智力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "智力", value: 2 },
  },
  {
    id: "helmet_hp_60",
    name: "頭盔體力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "HP", value: 10 },
  },
  {
    id: "helmet_def_60",
    name: "頭盔防禦力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "物防", value: 2 },
    secondaryEffects: [{ stat: "魔防", value: 2 }],
  },
  {
    id: "topwear_str_60",
    name: "上衣力量卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "力量", value: 2 },
  },
  {
    id: "topwear_luk_60",
    name: "上衣幸運卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "幸運", value: 2 },
  },
  {
    id: "topwear_hp_60",
    name: "上衣體力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "HP", value: 15 },
  },
  {
    id: "topwear_def_60",
    name: "上衣防禦力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "物防", value: 2 },
    secondaryEffects: [{ stat: "魔防", value: 1 }],
  },
  {
    id: "bottomwear_dex_60",
    name: "下衣敏捷性卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "敏捷", value: 2 },
    secondaryEffects: [{ stat: "命中率", value: 1 }],
  },
  {
    id: "bottomwear_hp_60",
    name: "下衣體力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "HP", value: 15 },
  },
  {
    id: "bottomwear_def_60",
    name: "下衣防禦力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "物防", value: 2 },
    secondaryEffects: [{ stat: "魔防", value: 1 }],
  },
  {
    id: "bottomwear_jump_60",
    name: "下衣跳躍力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "跳躍力", value: 2 },
    secondaryEffects: [{ stat: "迴避率", value: 1 }],
  },
  {
    id: "overall_dex_60",
    name: "套服敏捷卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "敏捷", value: 2 },
    secondaryEffects: [{ stat: "命中率", value: 1 }],
  },
  {
    id: "overall_int_60",
    name: "套服智力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "智力", value: 2 },
    secondaryEffects: [{ stat: "魔防", value: 1 }],
  },
  {
    id: "overall_luk_60",
    name: "套服幸運卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "幸運", value: 2 },
    secondaryEffects: [{ stat: "命中率", value: 1 }],
  },
  {
    id: "overall_def_60",
    name: "套服防禦力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "物防", value: 2 },
    secondaryEffects: [{ stat: "魔防", value: 1 }],
  },
  {
    id: "shoes_dex_60",
    name: "鞋子敏捷性卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SHOES,
    primaryEffect: { stat: "迴避率", value: 2 },
    secondaryEffects: [{ stat: "命中率", value: 1 }],
  },
  {
    id: "shoes_speed_60",
    name: "鞋子移動速度卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SHOES,
    primaryEffect: { stat: "速度", value: 2 },
  },
  {
    id: "shoes_jump_60",
    name: "鞋子跳躍力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SHOES,
    primaryEffect: { stat: "跳躍力", value: 2 },
    secondaryEffects: [{ stat: "敏捷", value: 1 }],
  },
  {
    id: "gloves_att_60",
    name: "手套攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.GLOVES,
    primaryEffect: { stat: "物攻", value: 2 },
  },
  {
    id: "gloves_dex_60",
    name: "手套敏捷性卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.GLOVES,
    primaryEffect: { stat: "命中率", value: 2 },
    secondaryEffects: [{ stat: "敏捷", value: 1 }],
  },
  {
    id: "gloves_hp_60",
    name: "手套體力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.GLOVES,
    primaryEffect: { stat: "HP", value: 15 },
  },
  {
    id: "cape_str_60",
    name: "披風力量卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "力量", value: 2 },
  },
  {
    id: "cape_dex_60",
    name: "披風敏捷性卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "敏捷", value: 2 },
  },
  {
    id: "cape_int_60",
    name: "披風智力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "智力", value: 2 },
  },
  {
    id: "cape_luk_60",
    name: "披風幸運卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "幸運", value: 2 },
  },
  {
    id: "cape_hp_60",
    name: "披風體力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "HP", value: 10 },
  },
  {
    id: "cape_mp_60",
    name: "披風魔力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "MP", value: 10 },
  },
  {
    id: "cape_def_60",
    name: "披風防禦力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "物防", value: 3 },
    secondaryEffects: [{ stat: "魔防", value: 1 }],
  },
  {
    id: "cape_mdef_60",
    name: "披風魔防卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "魔防", value: 3 },
    secondaryEffects: [{ stat: "物防", value: 1 }],
  },
  {
    id: "shield_str_60",
    name: "盾牌力量卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "力量", value: 2 },
  },
  {
    id: "shield_luk_60",
    name: "盾牌幸運卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "幸運", value: 2 },
  },
  {
    id: "shield_hp_60",
    name: "盾牌體力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "HP", value: 15 },
  },
  {
    id: "shield_def_60",
    name: "盾牌防禦力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "物防", value: 2 },
    secondaryEffects: [{ stat: "魔防", value: 1 }],
  },
  {
    id: "eye_dex_60",
    name: "眼部裝飾敏捷卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.EYE_ACCESSORY,
    primaryEffect: { stat: "敏捷", value: 2 },
  },
  {
    id: "eye_int_60",
    name: "眼部裝飾智力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.EYE_ACCESSORY,
    primaryEffect: { stat: "智力", value: 2 },
  },
  {
    id: "earring_dex_60",
    name: "耳環敏捷卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "敏捷", value: 2 },
  },
  {
    id: "earring_int_60",
    name: "耳環智力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "魔攻", value: 2 },
    secondaryEffects: [{ stat: "智力", value: 1 }],
  },
  {
    id: "earring_luk_60",
    name: "耳環幸運卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "幸運", value: 2 },
  },
  {
    id: "earring_hp_60",
    name: "耳環體力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "HP", value: 15 },
  },
  {
    id: "pendant_dex_60",
    name: "項鍊敏捷卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "敏捷", value: 2 },
  },
  {
    id: "pendant_luk_60",
    name: "項鍊幸運卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "幸運", value: 2 },
  },
  {
    id: "belt_dex_60",
    name: "腰帶敏捷卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.BELT,
    primaryEffect: { stat: "敏捷", value: 2 },
  },
  {
    id: "belt_int_60",
    name: "腰帶智力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.BELT,
    primaryEffect: { stat: "智力", value: 2 },
  },
  {
    id: "1h_sword_att_60",
    name: "單手劍攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_SWORD,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "1h_sword_acc_60",
    name: "單手劍命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_SWORD,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "2h_sword_att_60",
    name: "雙手劍攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_SWORD,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "2h_sword_acc_60",
    name: "雙手劍命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_SWORD,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "1h_axe_att_60",
    name: "單手斧攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_AXE,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "1h_axe_acc_60",
    name: "單手斧命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_AXE,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "2h_axe_att_60",
    name: "雙手斧攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_AXE,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "2h_axe_acc_60",
    name: "雙手斧命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_AXE,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "1h_bw_att_60",
    name: "單手棍攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_BW,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "1h_bw_acc_60",
    name: "單手棍命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_BW,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "2h_bw_att_60",
    name: "雙手棍攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_BW,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "2h_bw_acc_60",
    name: "雙手棍命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_BW,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "spear_att_60",
    name: "槍攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SPEAR,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "spear_acc_60",
    name: "槍命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.SPEAR,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "polearm_att_60",
    name: "矛攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.POLE_ARM,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "polearm_acc_60",
    name: "矛命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.POLE_ARM,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "bow_att_60",
    name: "弓攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.BOW,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "命中率", value: 1 }],
  },
  {
    id: "crossbow_att_60",
    name: "弩攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CROSSBOW,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "命中率", value: 1 }],
  },
  {
    id: "wand_matt_60",
    name: "短杖魔力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.WAND,
    primaryEffect: { stat: "魔攻", value: 2 },
    secondaryEffects: [{ stat: "智力", value: 1 }],
  },
  {
    id: "staff_matt_60",
    name: "長杖魔力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.STAFF,
    primaryEffect: { stat: "魔攻", value: 2 },
    secondaryEffects: [{ stat: "智力", value: 1 }],
  },
  {
    id: "dagger_att_60",
    name: "短劍攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.DAGGER,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "幸運", value: 1 }],
  },
  {
    id: "claw_att_60",
    name: "拳套攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.CLAW,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "命中率", value: 1 }],
  },
  {
    id: "knuckle_att_60",
    name: "指虎攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.KNUCKLE,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "knuckle_acc_60",
    name: "指虎命中率卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.KNUCKLE,
    primaryEffect: { stat: "命中率", value: 3 },
    secondaryEffects: [
      { stat: "敏捷", value: 2 },
      { stat: "物攻", value: 1 },
    ],
  },
  {
    id: "gun_att_60",
    name: "手槍攻擊力卷軸60%",
    successRate: 60,
    equipmentType: EQUIPMENT_TYPES.GUN,
    primaryEffect: { stat: "物攻", value: 2 },
    secondaryEffects: [{ stat: "命中率", value: 1 }],
  },

  // 100%成功率卷軸 (40種)
  {
    id: "helmet_dex_100",
    name: "頭盔敏捷卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "敏捷", value: 1 },
  },
  {
    id: "helmet_int_100",
    name: "頭盔智力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.HELMET,
    primaryEffect: { stat: "智力", value: 1 },
  },
  {
    id: "topwear_str_100",
    name: "上衣力量卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "力量", value: 1 },
  },
  {
    id: "topwear_luk_100",
    name: "上衣幸運卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.TOPWEAR,
    primaryEffect: { stat: "幸運", value: 1 },
  },
  {
    id: "bottomwear_dex_100",
    name: "下衣敏捷性卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "敏捷", value: 1 },
  },
  {
    id: "bottomwear_hp_100",
    name: "下衣體力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "HP", value: 5 },
  },
  {
    id: "bottomwear_jump_100",
    name: "下衣跳躍力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.BOTTOMWEAR,
    primaryEffect: { stat: "跳躍力", value: 1 },
  },
  {
    id: "overall_str_100",
    name: "套服力量卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "力量", value: 1 },
  },
  {
    id: "overall_int_100",
    name: "套服智力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "智力", value: 1 },
  },
  {
    id: "overall_luk_100",
    name: "套服幸運卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "幸運", value: 1 },
  },
  {
    id: "overall_def_100",
    name: "套服防禦力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.OVERALL,
    primaryEffect: { stat: "物防", value: 1 },
  },
  {
    id: "shoes_jump_100",
    name: "鞋子跳躍力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.SHOES,
    primaryEffect: { stat: "跳躍力", value: 1 },
  },
  {
    id: "gloves_hp_100",
    name: "手套體力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.GLOVES,
    primaryEffect: { stat: "HP", value: 5 },
  },
  {
    id: "cape_str_100",
    name: "披風力量卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "力量", value: 1 },
  },
  {
    id: "cape_dex_100",
    name: "披風敏捷性卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "敏捷", value: 1 },
  },
  {
    id: "cape_int_100",
    name: "披風智力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "智力", value: 1 },
  },
  {
    id: "cape_luk_100",
    name: "披風幸運卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "幸運", value: 1 },
  },
  {
    id: "cape_hp_100",
    name: "披風體力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "HP", value: 5 },
  },
  {
    id: "cape_mp_100",
    name: "披風魔力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.CAPE,
    primaryEffect: { stat: "MP", value: 10 },
  },
  {
    id: "shield_str_100",
    name: "盾牌力量卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "力量", value: 1 },
  },
  {
    id: "shield_luk_100",
    name: "盾牌幸運卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "幸運", value: 1 },
  },
  {
    id: "shield_hp_100",
    name: "盾牌體力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "HP", value: 5 },
  },
  {
    id: "shield_def_100",
    name: "盾牌防禦力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.SHIELD,
    primaryEffect: { stat: "物防", value: 1 },
  },
  {
    id: "earring_dex_100",
    name: "耳環敏捷卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "敏捷", value: 1 },
  },
  {
    id: "earring_luk_100",
    name: "耳環幸運卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "幸運", value: 1 },
  },
  {
    id: "earring_hp_100",
    name: "耳環體力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.EARRING,
    primaryEffect: { stat: "HP", value: 5 },
  },
  {
    id: "belt_str_100",
    name: "腰帶力量卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.BELT,
    primaryEffect: { stat: "力量", value: 1 },
  },
  {
    id: "belt_dex_100",
    name: "腰帶敏捷卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.BELT,
    primaryEffect: { stat: "敏捷", value: 1 },
  },
  {
    id: "belt_int_100",
    name: "腰帶智力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.BELT,
    primaryEffect: { stat: "智力", value: 1 },
  },
  {
    id: "belt_luk_100",
    name: "腰帶幸運卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.BELT,
    primaryEffect: { stat: "幸運", value: 1 },
  },
  {
    id: "1h_sword_acc_100",
    name: "單手劍命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_SWORD,
    primaryEffect: { stat: "命中率", value: 1 },
  },
  {
    id: "2h_sword_acc_100",
    name: "雙手劍命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_SWORD,
    primaryEffect: { stat: "命中率", value: 1 },
  },
  {
    id: "1h_axe_acc_100",
    name: "單手斧命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_AXE,
    primaryEffect: { stat: "命中率", value: 1 },
  },
  {
    id: "2h_axe_acc_100",
    name: "雙手斧命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_AXE,
    primaryEffect: { stat: "命中率", value: 1 },
  },
  {
    id: "1h_bw_acc_100",
    name: "單手棍命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.ONE_HANDED_BW,
    primaryEffect: { stat: "命中率", value: 1 },
  },
  {
    id: "2h_bw_att_100",
    name: "雙手棍攻擊力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_BW,
    primaryEffect: { stat: "物攻", value: 1 },
    secondaryEffects: [{ stat: "力量", value: 1 }],
  },
  {
    id: "2h_bw_acc_100_1",
    name: "雙手棍命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_BW,
    primaryEffect: { stat: "命中率", value: 1 },
  },
  {
    id: "2h_bw_acc_100_2",
    name: "雙手棍命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.TWO_HANDED_BW,
    primaryEffect: { stat: "命中率", value: 1 },
  },
  {
    id: "spear_acc_100",
    name: "槍命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.SPEAR,
    primaryEffect: { stat: "命中率", value: 1 },
  },
  {
    id: "bow_att_100",
    name: "弓攻擊力卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.BOW,
    primaryEffect: { stat: "物攻", value: 1 },
  },
  {
    id: "knuckle_acc_100",
    name: "指虎命中率卷軸100%",
    successRate: 100,
    equipmentType: EQUIPMENT_TYPES.KNUCKLE,
    primaryEffect: { stat: "命中率", value: 1 },
  },

  // 30%成功率卷軸 (8種)
  {
    id: "face_str_30",
    name: "臉飾力量卷軸30%",
    successRate: 30,
    equipmentType: EQUIPMENT_TYPES.FACE_ACCESSORY,
    primaryEffect: { stat: "力量", value: 3 },
  },
  {
    id: "face_dex_30",
    name: "臉飾敏捷卷軸30%",
    successRate: 30,
    equipmentType: EQUIPMENT_TYPES.FACE_ACCESSORY,
    primaryEffect: { stat: "敏捷", value: 3 },
  },
  {
    id: "face_int_30",
    name: "臉飾智力卷軸30%",
    successRate: 30,
    equipmentType: EQUIPMENT_TYPES.FACE_ACCESSORY,
    primaryEffect: { stat: "智力", value: 3 },
  },
  {
    id: "face_luk_30",
    name: "臉飾幸運卷軸30%",
    successRate: 30,
    equipmentType: EQUIPMENT_TYPES.FACE_ACCESSORY,
    primaryEffect: { stat: "幸運", value: 3 },
  },
  {
    id: "pendant_str_30",
    name: "項鍊力量卷軸30%",
    successRate: 30,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "力量", value: 3 },
  },
  {
    id: "pendant_dex_30",
    name: "項鍊敏捷卷軸30%",
    successRate: 30,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "敏捷", value: 3 },
  },
  {
    id: "pendant_int_30",
    name: "項鍊智力卷軸30%",
    successRate: 30,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "智力", value: 3 },
  },
  {
    id: "pendant_luk_30",
    name: "項鍊幸運卷軸30%",
    successRate: 30,
    equipmentType: EQUIPMENT_TYPES.PENDANT,
    primaryEffect: { stat: "幸運", value: 3 },
  },
];

// 根據裝備類型過濾卷軸的工具函數
export const getScrollsForEquipmentType = (equipmentType: string): Scroll[] => {
  return SCROLLS.filter((scroll) => scroll.equipmentType === equipmentType);
};

// 獲取所有可用的裝備類型
export const getAvailableEquipmentTypes = (): string[] => {
  const equipmentTypes = new Set(SCROLLS.map((scroll) => scroll.equipmentType));
  return Array.from(equipmentTypes);
};

// 根據成功率過濾卷軸
export const getScrollsBySuccessRate = (successRate: number): Scroll[] => {
  return SCROLLS.filter((scroll) => scroll.successRate === successRate);
};

// 根據裝備類型獲取可用的屬性列表
export const getAvailableAttributesForEquipment = (
  equipmentType: string
): string[] => {
  if (!equipmentType) return [];

  const scrolls = getScrollsForEquipmentType(equipmentType);
  const attributes = new Set<string>();

  scrolls.forEach((scroll) => {
    // 添加主要效果的屬性
    attributes.add(scroll.primaryEffect.stat);

    // 添加次要效果的屬性
    if (scroll.secondaryEffects) {
      scroll.secondaryEffects.forEach((effect) => {
        attributes.add(effect.stat);
      });
    }
  });

  return Array.from(attributes).sort();
};
